language: c

env:
  global:
  - CACHE=$HOME/.ricobot-caches

cache:
  branch: md5deep
  directories:
  - "$CACHE"

before_script:
  - mkdir deploy
  - git clone https://github.com/Bots-United/hlsdk
  - git clone https://github.com/Bots-United/metamod-hl1

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    addons:
      apt:
        packages:
        - libc6-dev-i386
        - lib32gcc-4.8-dev
        - lib32stdc++-4.8-dev
        - g++-multilib
        - zip
    script:
      - make OPT=opt SDKTOP=./hlsdk METAMODDIR=./metamod-hl1/metamod
      - zip -9 -j ./deploy/ricobot-mm-linux-i386.zip *.so *.txt README

  - os: linux
    dist: trusty
    addons:
      apt:
        packages:
        - binutils-mingw-w64-i686
        - gcc-mingw-w64-i686
        - g++-mingw-w64-i686
        - zip
    script:
      - make -fMakefile.mingw SDKTOP=./hlsdk METAMODDIR=./metamod-hl1/metamod
      - zip -9 -j ./deploy/ricobot-mm-win32.zip *.dll *.txt README

  - os: osx
    osx_image: xcode8
    language: objective-c
    script:
      - make OPT=opt SDKTOP=./hlsdk METAMODDIR=./metamod-hl1/metamod
      - zip -9 -j ./deploy/ricobot-mm-macos.zip *.dylib *.txt README

before_deploy:
  - sed=sed; date=date
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
        brew update
        brew install gnu-sed
        sed=gsed
        date=gdate
    fi
  - DATE=$($date -d $(git show -s --format=%cI) "+%F")
  - COMMIT=$(git rev-parse --short HEAD)
  - |
    $sed -i "
    s/@VERSION@/v$DATE-g$COMMIT-$TRAVIS_BRANCH/g
    s/@DESC@/$(echo -n $TRAVIS_COMMIT_MESSAGE|tr '\n' ';'|sed -e 's@[\\"]@\\&@g;s@[/&\$]@\\&@g')/g
    s/@RELEASE_DATE@/$(git show -s --format=%cI)/g
    s/@VCS_TAG@/$(git describe --tags)/g
    s/@AUTHOR@/$(git show -s --format=%an)/g
    s/@AUTHOR_DATE@/$(git show -s --format=%ai)/g
    s/@COMMITER@/$(git show -s --format=%cn)/g
    s/@BRANCH@/$TRAVIS_BRANCH/g
    s/@COMMITID@/$(git show -s --format=%h)/g
    " bintray.json
  - cat bintray.json

deploy:
  - provider: releases
    api_key:
      secure: cd+0SpJbYC3f7hlmYbEU/KQhX8ZU2itDyWBhV9EO1J52BWTRKPaxfmwwKKChDDLExizM8P9fbCgv1BslzJ69u4AUSAiqbNpEll/Yhdh/sLM3BmHC4KPTbRnT0h/5aIKeI89oXt1ftw2p8DBL7k+a6RCYIm44q/CkLL5v7G9/q9tNYrnCjD0SB6DT8WyOlZaq/6Pw6uCd7Sopw6gIHJoiHO02fEzr0DkKG9DKi9KlNKgW56g0DffC+jNvj+YhrLk1AHNVZHKbLlMk8ClcOwnTPTXQmEAl2gmGZPKGfNo5LTz3REzkuD6Q4msf0ENFd3fh8xUeIXZw7EeihnaIuyz1ZcRVpBdt1t69OYrSGMTjANuq2V7g98Qqh9MDDD4A2kVi1YiiMOjBCM6chDZEgKeGsl9Rqdx2G+ZS1ETc/qsLMzWrzHBhvNCqissqfqY/sQ7Uio8dEHQ50n4A8N9eff7HKfHNjRmHdHZfQRIKDOi7F+i+xxdk44WJTf4vqT22f8Q6BjDdUluXJMHf2RcFRGKJ8eUDH2FkXw+QCmSlkbXoEI0SQ+ZPd7YDyY7+0AefvShReeqwJFItCLFKwbvBNRduYnIZC8te81DFp6Wmw+CdS6VYZssk1zttH0dq19z7SW31sVZ4iKTl5AN1bT++gYF9rNwHBXYmqVoshWi8+XagbUM=
    file: deploy/*
    file_glob: true
    skip_cleanup: true
    overwrite: true
    on:
      all_branches: true
      tags: true

  - provider: bintray
    user: cecilharvey
    key:
      secure: EXLmV2eOni1K/bZ8MkAktGSV4Oql1HY6i1JvXzALlGtUZrvRqUdgXyEiN4HAYcFxzwh/sk4T9k8vLPMeWQ6Ry7gABj+N5DICSTVTGuJ766kxlOx6gVIgiFmOAnZ1lMn1dPEOX56y8BVpEMmsZxMOjmwo4dC7AwHCS1WXpr09dqTyLVriwZjJ7+0gCNuko4Tm+vC8SgeS6PDzYz5qS+UxvJCEAYgeoJPli/p0cjfsLL04cXzjGS8CCzIFLplHuPDut2za+y8NBtkf6Z3jY7H6LNrPMG32vP7QjW0P53V0giiz/cE7lc0DGvYinISblT1SF1Zr/uqJ+4C3dcgrv9tpVLzakybyfjHv5JsBba2j7Xh77lpiZMkJvyn2e1ar6HWWBlpaklsE3G8FZlKqO9twGCRlsf0/wiUr2Ni8b17BkTYROG/WDfa4xFh0RSUQczPilT/QB1RklC7jGSjMR7NFTpnKxf8QuUSRFSkljvN+CbQtC56LVJZnrKps3wzZOdpWxGzVy8FDcyxjbbqLpXiHw1T6vFE5E9XNCmobebNdpxkHo2kNwS0Mnb+w8G8HV4+FnH2s6BSzwnxLPwkrfxlgvMVOi6KCPmjzhFjklRkxqVQuh3sMt9tmpMSnZpUeJ+kHQA8eV1uslvYX+Ker4drzTvDGC7mgWIOtHIWCK/Ob32Y=
    file: bintray.json
    skip_cleanup: true
    on:
      all_branches: true

